version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - VITE_UNSPLASH_ACCESS_KEY=${VITE_UNSPLASH_ACCESS_KEY}
    restart: unless-stopped
    depends_on:
      - backend
